using System.Text.RegularExpressions;

namespace MacroButtons.Models;

/// <summary>
/// Defines a dynamic title that is generated by executing a command.
/// </summary>
public class TitleDefinition
{
    /// <summary>
    /// Python script to execute. First element is script path, rest are arguments.
    /// </summary>
    public List<string>? Python { get; set; }

    /// <summary>
    /// Executable to run. First element is exe path, rest are arguments.
    /// </summary>
    public List<string>? Exe { get; set; }

    /// <summary>
    /// Builtin command to execute (e.g., "clock()").
    /// </summary>
    public string? Builtin { get; set; }

    /// <summary>
    /// Optional refresh interval override (e.g., "100ms", "1s", "5m").
    /// If not specified, uses global refresh interval.
    /// Minimum is 100ms.
    /// </summary>
    public string? Refresh { get; set; }

    /// <summary>
    /// Optional theme name to apply to this dynamic title (e.g., "prominent", "toggled").
    /// If not specified, uses the ButtonItem's theme or "default".
    /// This theme can still be overridden by JSON output from the command (fg/bg properties).
    /// </summary>
    public string? Theme { get; set; }

    /// <summary>
    /// Returns true if this is a Python-based dynamic title.
    /// </summary>
    public bool IsPython => Python != null && Python.Count > 0;

    /// <summary>
    /// Returns true if this is an executable-based dynamic title.
    /// </summary>
    public bool IsExecutable => Exe != null && Exe.Count > 0;

    /// <summary>
    /// Returns true if this is a builtin-based dynamic title.
    /// </summary>
    public bool IsBuiltin => !string.IsNullOrEmpty(Builtin);

    /// <summary>
    /// Parses the refresh interval string into a TimeSpan.
    /// Supports formats: "100ms", "5s", "1m", "2h"
    /// Returns null if no refresh override is specified.
    /// </summary>
    public TimeSpan? GetRefreshInterval()
    {
        if (string.IsNullOrWhiteSpace(Refresh))
            return null;

        var match = Regex.Match(Refresh, @"^(\d+)(ms|s|m|h)$");
        if (!match.Success)
            return null;

        var value = int.Parse(match.Groups[1].Value);
        var unit = match.Groups[2].Value;

        var interval = unit switch
        {
            "ms" => TimeSpan.FromMilliseconds(value),
            "s" => TimeSpan.FromSeconds(value),
            "m" => TimeSpan.FromMinutes(value),
            "h" => TimeSpan.FromHours(value),
            _ => (TimeSpan?)null
        };

        // Enforce minimum of 100ms
        if (interval.HasValue && interval.Value.TotalMilliseconds < 100)
            return TimeSpan.FromMilliseconds(100);

        return interval;
    }
}
