namespace MacroButtons.Models;

/// <summary>
/// Defines a dynamic title that is generated by executing a command.
/// </summary>
public class TitleDefinition
{
    /// <summary>
    /// Python script to execute. First element is script path, rest are arguments.
    /// </summary>
    public List<string>? Python { get; set; }

    /// <summary>
    /// Executable to run. First element is exe path, rest are arguments.
    /// </summary>
    public List<string>? Exe { get; set; }

    /// <summary>
    /// Returns true if this is a Python-based dynamic title.
    /// </summary>
    public bool IsPython => Python != null && Python.Count > 0;

    /// <summary>
    /// Returns true if this is an executable-based dynamic title.
    /// </summary>
    public bool IsExecutable => Exe != null && Exe.Count > 0;
}
